#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Robbie Smith <zoqaeski@gmail.com>
#
# Modified to make powerlevel10k start earlier in the hope that this will speed
# up the opening of new shells.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Source VTE.sh for better VTE support
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi

# Add Keychain support
eval $(keychain --eval --quiet --agents ssh,gpg id_ed25519)

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Customize to your needs...
# Base16 Shell
BASE16_SHELL=$HOME/.local/share/themes/base16/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

alias xevk="xev | sed -ne '/^KeyPress/,/^$/p'"

# Enables shallow copies on filesystems that support it (CoW)
alias cp="${aliases[cp]:-cp} --reflink=auto"


alias gpg-master='gpg --homedir /mnt/gpg-key-backup/gnupghome'

# Battery stats
if (( $+commands[tlp] )); then
  alias tlp-bat='sudo tlp-stat -b | grep --color=never -i charge'
fi

# Alias for arara-git
# alias arara='arara-git'

# FZF conveniences
# source /usr/share/fzf/completion.zsh
# source /usr/share/fzf/key-bindings.zsh

# Reload environment
#bindkey "$key_info[Control]X$key_info[Control]R" "eval $(tmux switch-client \; show-environment -s)"
#


function add-replay-gain () {
  local curr=$(pwd)
  echo "Loading albums…"
  local albums=("${(@f)$(find "${curr}" -type f -iname '*.flac' -exec dirname '{}' \; | sort -u)}")
  for a in $albums[@] ; do
    cd "${a}"
    echo "Adding ReplayGain tags to ${a}"
    metaflac --add-replay-gain *.flac
    cd "${curr}"
  done
}

# Override texdoc with fzf mode
if (( $+commands[fzf] )); then
  alias oldtexdoc='/usr/local/bin/texdoc'
  function texdoc () { 
    IFS='
    '
    local declare files=($(/usr/local/bin/texdoc -l -M "$1" | cut -f3 | fzf --exit-0 --multi))
    [[ -n "$files" ]] && o "${files[@]}"
    unset IFS
  }
fi

# Quickly browse all packages installed with pacman using fzf
# (Found in the Arch wiki)
if (( $+commands[fzf] )); then
  function pacbrowse() {
    pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
  }
fi


#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

# depends on p7zip (7z command) with rar support
# should be compatible with bash (tested on zsh)
# for batch call:
# find -name '*.cbr' -print -exec zsh -c 'source ~/.zshrc;cbr2cbz "{}"' \;

function cbr2cbz() {
  TMP="$XDG_RUNTIME_DIR"
  CBZ=$(basename "$1" .cbr).cbz
  DN=$(dirname "$1")
  if [ -f "$DN/$CBZ" ]; then
    echo "$DN/$CBZ already exists"
  else
    echo "Will create $DN/$CBZ"
    DIR=$(mktemp -d -p "$TMP")
    7z x "$1" -o"$DIR"
    # find "$DIR" -type f -print
    find "$DIR" -type f -print -exec 7z a -tzip "$DN/$CBZ" {} +
    rm -rf "$DIR"
  fi
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
